Models/Car.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DotnetMvcDemoCars.Models
{
    public class Car
    {
        [Key]
        public int Id {get; set;}
        
        [Required]
        public string Name { get; set; }

        [Display(Name = "Doors Number")]
        public int doorsNumber { get; set; }

        [Display(Name = "Distance Travelled")]
        public int distanceTravelled {get; set;}

        [Display(Name = "Produce Date")]
        [DataType(DataType.Date)]
        public DateTime ProduceDate { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace DotnetMvcDemoCars.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SeedDatabaseWithData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using DotnetMvcDemoCars.Data;
using System;
using System.Linq;

namespace DotnetMvcDemoCars.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MvcCarContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<MvcCarContext>>()))
            {

                if (context.Car.Any())
                {
                    return;   
                }

                context.Car.AddRange(
                    new Car
                    {
                        Name = "Audi A3",
                        doorsNumber = 5,
                        distanceTravelled = 140221,
                        ProduceDate = DateTime.Parse("2020-12-10")
                    },
                    new Car
                    {
                        Name = "Fiat Bravo",
                        doorsNumber = 3,
                        distanceTravelled = 240252,
                        ProduceDate = DateTime.Parse("2016-01-16")
                    },
                    new Car
                    {
                        Name = "Citroen C2",
                        doorsNumber = 3,
                        distanceTravelled = 340274,
                        ProduceDate = DateTime.Parse("2002-02-08")
                    },
                    new Car
                    {
                        Name = "Volkswagen Polo",
                        doorsNumber = 5,
                        distanceTravelled = 154714,
                        ProduceDate = DateTime.Parse("2015-05-11")
                    }
                );
                context.SaveChanges();
            }
        }
    }
}

Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DotnetMvcDemoCars.Data;
using DotnetMvcDemoCars.Models;

namespace DotnetMvcDemoCars.Controllers
{
    public class CarController : Controller
    {
        private readonly MvcCarContext _context;

        public CarController(MvcCarContext context)
        {
            _context = context;
        }

        // GET: Car
        public async Task<IActionResult> Index()
        {
            return View(await _context.Car.ToListAsync());
        }

        // GET: Car/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Car/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Car/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,doorsNumber,distanceTravelled,ProduceDate")] Car car)
        {
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Car/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Car/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,doorsNumber,distanceTravelled,ProduceDate")] Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Car/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Car.FindAsync(id);
            _context.Car.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Car.Any(e => e.Id == id);
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DotnetMvcDemoCars.Data;
using DotnetMvcDemoCars.Models;


namespace DotnetMvcDemoCars.Controllers
{
    public class ContactController : Controller
    {
         public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DotnetMvcDemoCars.Models;

namespace DotnetMvcDemoCars.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Car/Create.cshtml
@model DotnetMvcDemoCars.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="doorsNumber" class="control-label"></label>
                <input asp-for="doorsNumber" class="form-control" />
                <span asp-validation-for="doorsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="distanceTravelled" class="control-label"></label>
                <input asp-for="distanceTravelled" class="form-control" />
                <span asp-validation-for="distanceTravelled" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProduceDate" class="control-label"></label>
                <input asp-for="ProduceDate" class="form-control" />
                <span asp-validation-for="ProduceDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Car/Delete.cshtml
@model DotnetMvcDemoCars.Models.Car

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.doorsNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.doorsNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.distanceTravelled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.distanceTravelled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProduceDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProduceDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Car/Details.cshtml
@model DotnetMvcDemoCars.Models.Car

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.doorsNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.doorsNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.distanceTravelled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.distanceTravelled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProduceDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProduceDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a> 
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Views/Car/Edit.cshtml
@model DotnetMvcDemoCars.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="doorsNumber" class="control-label"></label>
                <input asp-for="doorsNumber" class="form-control" />
                <span asp-validation-for="doorsNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="distanceTravelled" class="control-label"></label>
                <input asp-for="distanceTravelled" class="form-control" />
                <span asp-validation-for="distanceTravelled" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProduceDate" class="control-label"></label>
                <input asp-for="ProduceDate" class="form-control" />
                <span asp-validation-for="ProduceDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Car/Index.cshtml
@model IEnumerable<DotnetMvcDemoCars.Models.Car>

@{
    ViewData["Title"] = "Car";
}

<h1 style="text-align: center">Car catalog</h1>
<br>
<br>

<p>
    <a asp-action="Create" class="btn btn-success">New Car</a>
</p>
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.doorsNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.distanceTravelled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProduceDate)
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doorsNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.distanceTravelled) km
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProduceDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a> 
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Contact Page";
}

<div class="text-center">
    <h3 class="display-4">Contact</h1>
    <br>
</div>

<div>
    <hr>
    <h5>Tel: 123-456-789</h3>
    <hr>
    <h5>Address: ul. abc 12, Warszawa</h3>
    <hr>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>


<img class="home_image" src="images/car-racing-4394450_1920.jpg">

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotnetMvcDemoCars</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!--- <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DotnetMvcDemoAppCars</a> --->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"> Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index"> Cars </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index"> Contact </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"> Privacy </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DotnetMvcDemoCars - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>